import { useState, useCallback, useEffect } from "react";
import { saveProfile, saveNutritionDay, saveWorkout, saveMeasure, saveRoutine, saveRacePlan, saveWater, saveSleep, saveCustomFoods } from "./db.js";
import SettingsScreen from "./SettingsScreen.jsx";

// ═══════════════════════════════════════════════════════════════════════════
// BASE DE DATOS Y LÓGICA — SMINK FIT
// ═══════════════════════════════════════════════════════════════════════════

const FOOD_DB = [
  // HIDRATOS
  { id:"arr1", name:"Arroz blanco", cat:"hidrato", kcal:360, p:7, g:1, c:80 },
  { id:"arr2", name:"Arroz integral", cat:"hidrato", kcal:340, p:8, g:2, c:72 },
  { id:"pas1", name:"Pasta (espaguetis)", cat:"hidrato", kcal:358, p:12, g:1, c:72 },
  { id:"pas2", name:"Pasta integral", cat:"hidrato", kcal:340, p:13, g:2, c:68 },
  { id:"pas3", name:"Macarrones", cat:"hidrato", kcal:358, p:12, g:1, c:72 },
  { id:"gno1", name:"Ñoquis Hacendado", cat:"hidrato", kcal:174, p:4, g:0, c:37 },
  { id:"pat1", name:"Patata cruda", cat:"hidrato", kcal:77, p:2, g:0, c:17 },
  { id:"pat2", name:"Boniato crudo", cat:"hidrato", kcal:86, p:2, g:0, c:20 },
  { id:"tor1", name:"Tortitas maíz Hacendado natural", cat:"hidrato", kcal:367, p:8, g:2, c:80 },
  { id:"tor2", name:"Tortitas maíz sabor jamón", cat:"hidrato", kcal:417, p:8, g:5, c:80 },
  { id:"tor3", name:"Bicentury tomate", cat:"hidrato", kcal:460, p:6, g:14, c:72 },
  { id:"faj1", name:"Fajitas pequeñas Hacendado", cat:"hidrato", kcal:287, p:8, g:5, c:55 },
  { id:"faj2", name:"Fajitas avena 51% Hacendado", cat:"hidrato", kcal:287, p:15, g:6, c:40 },
  { id:"pan1", name:"Pan centeno 51% Mercadona", cat:"hidrato", kcal:262, p:9, g:2, c:50 },
  { id:"pan2", name:"Pan 12 cereales Hacendado", cat:"hidrato", kcal:263, p:10, g:4, c:47 },
  { id:"pan3", name:"Pan de molde integral", cat:"hidrato", kcal:247, p:9, g:3, c:46 },
  { id:"pan4", name:"Pan blanco de molde", cat:"hidrato", kcal:265, p:8, g:3, c:51 },
  { id:"ave1", name:"Avena en copos", cat:"hidrato", kcal:370, p:13, g:7, c:63 },
  { id:"qui1", name:"Quinoa cruda (en seco)", cat:"hidrato", kcal:368, p:14, g:6, c:64 },
  { id:"len1", name:"Lentejas crudas (en seco)", cat:"hidrato", kcal:336, p:24, g:1, c:60 },
  { id:"gar1", name:"Garbanzos crudos (en seco)", cat:"hidrato", kcal:364, p:19, g:6, c:61 },
  { id:"mai1", name:"Maíz dulce (lata escurrido)", cat:"hidrato", kcal:86, p:3, g:1, c:19 },
  { id:"cop1", name:"Copos de maíz (cornflakes)", cat:"hidrato", kcal:357, p:7, g:1, c:80 },
  // PROTEÍNAS
  { id:"pol1", name:"Pechuga de pollo", cat:"proteina", kcal:165, p:31, g:4, c:0 },
  { id:"pol2", name:"Muslo de pollo sin piel", cat:"proteina", kcal:177, p:25, g:8, c:0 },
  { id:"sal1", name:"Salmón fresco", cat:"proteina", kcal:208, p:20, g:13, c:0 },
  { id:"sal2", name:"Salmón ahumado", cat:"proteina", kcal:172, p:25, g:8, c:0 },
  { id:"mer1", name:"Merluza", cat:"proteina", kcal:80, p:17, g:2, c:0 },
  { id:"bac1", name:"Bacalao", cat:"proteina", kcal:82, p:18, g:1, c:0 },
  { id:"atu1", name:"Atún en conserva (agua)", cat:"proteina", kcal:116, p:26, g:1, c:0 },
  { id:"atu2", name:"Atún en aceite", cat:"proteina", kcal:200, p:29, g:9, c:0 },
  { id:"ter1", name:"Ternera molida 5%", cat:"proteina", kcal:137, p:21, g:5, c:0 },
  { id:"ter2", name:"Filete de ternera", cat:"proteina", kcal:150, p:22, g:6, c:0 },
  { id:"pav1", name:"Pechuga de pavo", cat:"proteina", kcal:135, p:29, g:2, c:0 },
  { id:"lom1", name:"Lomo embuchado", cat:"proteina", kcal:175, p:29, g:6, c:0 },
  { id:"emb1", name:"Embutido de pavo 93%", cat:"proteina", kcal:100, p:19, g:2, c:1 },
  { id:"hue1", name:"Huevo entero", cat:"proteina", kcal:155, p:13, g:11, c:1 },
  { id:"cla1", name:"Clara de huevo", cat:"proteina", kcal:52, p:11, g:0, c:1 },
  { id:"que1", name:"Queso cottage", cat:"proteina", kcal:98, p:11, g:4, c:3 },
  { id:"que2", name:"Queso light en lonchas", cat:"proteina", kcal:200, p:25, g:10, c:2 },
  { id:"yog1", name:"Yogur griego 0%", cat:"proteina", kcal:57, p:10, g:0, c:4 },
  { id:"yog2", name:"Yogur griego natural", cat:"proteina", kcal:97, p:9, g:5, c:4 },
  { id:"sar1", name:"Sardinas en conserva", cat:"proteina", kcal:185, p:25, g:10, c:0 },
  { id:"cer1", name:"Cerdo solomillo", cat:"proteina", kcal:143, p:22, g:6, c:0 },
  { id:"gam1", name:"Gambas", cat:"proteina", kcal:85, p:18, g:1, c:0 },
  // GRASAS
  { id:"aov1", name:"Aceite de oliva virgen extra", cat:"grasa", kcal:900, p:0, g:100, c:0 },
  { id:"agu1", name:"Aguacate", cat:"grasa", kcal:160, p:2, g:15, c:9 },
  { id:"nue1", name:"Nueces", cat:"grasa", kcal:654, p:15, g:65, c:14 },
  { id:"alm1", name:"Almendras", cat:"grasa", kcal:579, p:21, g:50, c:22 },
  { id:"cac1", name:"Cacahuetes", cat:"grasa", kcal:567, p:26, g:49, c:16 },
  { id:"man1", name:"Mantequilla de cacahuete", cat:"grasa", kcal:588, p:25, g:50, c:20 },
  { id:"sem1", name:"Semillas de chía", cat:"grasa", kcal:486, p:17, g:31, c:42 },
  { id:"sem2", name:"Semillas de lino", cat:"grasa", kcal:534, p:18, g:42, c:29 },
  { id:"hum1", name:"Hummus", cat:"grasa", kcal:177, p:5, g:10, c:17 },
  { id:"que3", name:"Queso parmesano", cat:"grasa", kcal:431, p:38, g:29, c:4 },
  // VERDURAS
  { id:"tom1", name:"Tomate cherry", cat:"verdura", kcal:18, p:1, g:0, c:4 },
  { id:"tom2", name:"Tomate natural", cat:"verdura", kcal:18, p:1, g:0, c:4 },
  { id:"ceb1", name:"Cebolla", cat:"verdura", kcal:40, p:1, g:0, c:9 },
  { id:"lec1", name:"Lechuga", cat:"verdura", kcal:15, p:1, g:0, c:2 },
  { id:"esp1", name:"Espárragos", cat:"verdura", kcal:20, p:2, g:0, c:4 },
  { id:"cha1", name:"Champiñones", cat:"verdura", kcal:22, p:3, g:0, c:3 },
  { id:"jud1", name:"Judías verdes", cat:"verdura", kcal:31, p:2, g:0, c:7 },
  { id:"bro1", name:"Brócoli", cat:"verdura", kcal:34, p:3, g:0, c:7 },
  { id:"cal1", name:"Calabacín", cat:"verdura", kcal:17, p:1, g:0, c:3 },
  { id:"pip1", name:"Pimiento rojo", cat:"verdura", kcal:31, p:1, g:0, c:6 },
  { id:"pip2", name:"Pimiento verde", cat:"verdura", kcal:20, p:1, g:0, c:4 },
  { id:"zah1", name:"Zanahoria", cat:"verdura", kcal:41, p:1, g:0, c:10 },
  { id:"col1", name:"Coliflor", cat:"verdura", kcal:25, p:2, g:0, c:5 },
  { id:"ber1", name:"Berenjena", cat:"verdura", kcal:24, p:1, g:0, c:6 },
  { id:"ace1", name:"Acelgas", cat:"verdura", kcal:19, p:2, g:0, c:4 },
  { id:"esp2", name:"Espinacas", cat:"verdura", kcal:23, p:3, g:0, c:4 },
  { id:"pep1", name:"Pepino", cat:"verdura", kcal:15, p:1, g:0, c:4 },
  { id:"col2", name:"Col (repollo)", cat:"verdura", kcal:25, p:1, g:0, c:6 },
  // POSTRE
  { id:"ypos1", name:"Yogur griego 0%", cat:"postre", kcal:57, p:10, g:0, c:4 },
  { id:"ypos2", name:"Yogur griego natural", cat:"postre", kcal:97, p:9, g:5, c:4 },
  { id:"ypos3", name:"Yogur natural azucarado", cat:"postre", kcal:75, p:4, g:3, c:9 },
  { id:"ypos4", name:"Yogur proteico", cat:"postre", kcal:60, p:10, g:0, c:5 },
  { id:"lec1p", name:"Leche entera", cat:"postre", kcal:61, p:3, g:3, c:5 },
  { id:"lec2p", name:"Leche semidesnatada", cat:"postre", kcal:46, p:3, g:2, c:5 },
  { id:"lec3p", name:"Leche desnatada", cat:"postre", kcal:35, p:3, g:0, c:5 },
  { id:"lec4p", name:"Leche de avena", cat:"postre", kcal:43, p:1, g:1, c:7 },
  { id:"lec5p", name:"Leche de almendras sin azúcar", cat:"postre", kcal:13, p:0, g:1, c:0 },
  { id:"cor1p", name:"Cornflakes (copos de maíz)", cat:"postre", kcal:357, p:7, g:1, c:80 },
  { id:"cor2p", name:"Cornflakes chocolate", cat:"postre", kcal:380, p:6, g:3, c:78 },
  { id:"ave1p", name:"Avena en copos", cat:"postre", kcal:370, p:13, g:7, c:63 },
  { id:"gra1p", name:"Granola", cat:"postre", kcal:480, p:10, g:20, c:60 },
